<p>
    <label>Provincia</label>
    <select name="province">
        <option selected value="">Seleziona</option>
        <option value="[Abruzzo] Chieti">[Abruzzo] Chieti</option>
        <option value="[Abruzzo] L'Aquila">[Abruzzo] L'Aquila</option>
        <option value="[Abruzzo] Pescara">[Abruzzo] Pescara</option>
        <option value="[Abruzzo] Teramo">[Abruzzo] Teramo</option>
        <option value="[Basilicata] Matera">[Basilicata] Matera</option>
        <option value="[Basilicata] Potenza">[Basilicata] Potenza</option>
        <option value="[Calabria] Catanzaro">[Calabria] Catanzaro</option>
        <option value="[Calabria] Cosenza">[Calabria] Cosenza</option>
        <option value="[Calabria] Crotone">[Calabria] Crotone</option>
        <option value="[Calabria] Reggio Calabria">[Calabria] Reggio Calabria</option>
        <option value="[Calabria] Vibo Valenzia">[Calabria] Vibo Valenzia</option>
        <option value="[Campania] Avellino">[Campania] Avellino</option>
        <option value="[Campania] Benevento">[Campania] Benevento</option>
        <option value="[Campania] Caserta">[Campania] Caserta</option>
        <option value="[Campania] Napoli">[Campania] Napoli</option>
        <option value="[Campania] Salerno">[Campania] Salerno</option>
        <option value="[Emilia Romagna] Bologna">[Emilia Romagna] Bologna</option>
        <option value="[Emilia Romagna] Ferrara">[Emilia Romagna] Ferrara</option>
        <option value="[Emilia Romagna] Forlì">[Emilia Romagna] Forlì</option>
        <option value="[Emilia Romagna] Modena">[Emilia Romagna] Modena</option>
        <option value="[Emilia Romagna] Parma">[Emilia Romagna] Parma</option>
        <option value="[Emilia Romagna] Piacenza">[Emilia Romagna] Piacenza</option>
        <option value="[Emilia Romagna] Ravenna">[Emilia Romagna] Ravenna</option>
        <option value="[Emilia Romagna] Reggio Emilia">[Emilia Romagna] Reggio Emilia</option>
        <option value="[Emilia Romagna] Rimini">[Emilia Romagna] Rimini</option>
        <option value="[Emilia Romagna] San Marino">[Emilia Romagna] San Marino</option>
        <option value="[Friuli Venezia Giulia] Gorizia">[Friuli Venezia Giulia] Gorizia</option>
        <option value="[Friuli Venezia Giulia] Pordenone">[Friuli Venezia Giulia] Pordenone</option>
        <option value="[Friuli Venezia Giulia] Trieste">[Friuli Venezia Giulia] Trieste</option>
        <option value="[Friuli Venezia Giulia] Udine">[Friuli Venezia Giulia] Udine</option>
        <option value="[Lazio] Frosinone">[Lazio] Frosinone</option>
        <option value="[Lazio] Latina">[Lazio] Latina</option>
        <option value="[Lazio] Rieti">[Lazio] Rieti</option>
        <option value="[Lazio] Roma">[Lazio] Roma</option>
        <option value="[Lazio] Viterbo">[Lazio] Viterbo</option>
        <option value="[Liguria] Genova">[Liguria] Genova</option>
        <option value="[Liguria] Imperia">[Liguria] Imperia</option>
        <option value="[Liguria] La Spezia">[Liguria] La Spezia</option>
        <option value="[Liguria] Savona">[Liguria] Savona</option>
        <option value="[Lombardia] Bergamo">[Lombardia] Bergamo</option>
        <option value="[Lombardia] Brescia">[Lombardia] Brescia</option>
        <option value="[Lombardia] Como">[Lombardia] Como</option>
        <option value="[Lombardia] Cremona">[Lombardia] Cremona</option>
        <option value="[Lombardia] Lecco">[Lombardia] Lecco</option>
        <option value="[Lombardia] Lodi">[Lombardia] Lodi</option>
        <option value="[Lombardia] Mantova">[Lombardia] Mantova</option>
        <option value="[Lombardia] Milano">[Lombardia] Milano</option>
        <option value="[Lombardia] Pavia">[Lombardia] Pavia</option>
        <option value="[Lombardia] Sondrio">[Lombardia] Sondrio</option>
        <option value="[Lombardia] Varese">[Lombardia] Varese</option>
        <option value="[Marche] Ancona">[Marche] Ancona</option>
        <option value="[Marche] Ascoli Piceno">[Marche] Ascoli Piceno</option>
        <option value="[Marche] Macerata">[Marche] Macerata</option>
        <option value="[Marche] Pesaro">[Marche] Pesaro</option>
        <option value="[Molise] Campobasso">[Molise] Campobasso</option>
        <option value="[Molise] Isernia">[Molise] Isernia</option>
        <option value="[Piemonte] Alessandria">[Piemonte] Alessandria</option>
        <option value="[Piemonte] Asti">[Piemonte] Asti</option>
        <option value="[Piemonte] Biella">[Piemonte] Biella</option>
        <option value="[Piemonte] Cuneo">[Piemonte] Cuneo</option>
        <option value="[Piemonte] Novara">[Piemonte] Novara</option>
        <option value="[Piemonte] Torino">[Piemonte] Torino</option>
        <option value="[Piemonte] Verbania">[Piemonte] Verbania</option>
        <option value="[Piemonte] Vercelli">[Piemonte] Vercelli</option>
        <option value="[Puglia] Bari">[Puglia] Bari</option>
        <option value="[Puglia] Brindisi">[Puglia] Brindisi</option>
        <option value="[Puglia] Foggia">[Puglia] Foggia</option>
        <option value="[Puglia] Lecce">[Puglia] Lecce</option>
        <option value="[Puglia] Taranto">[Puglia] Taranto</option>
        <option value="[Sardegna] Cagliari">[Sardegna] Cagliari</option>
        <option value="[Sardegna] Nuoro">[Sardegna] Nuoro</option>
        <option value="[Sardegna] Oristano">[Sardegna] Oristano</option>
        <option value="[Sardegna] Sassari">[Sardegna] Sassari</option>
        <option value="[Sicilia] Agrigento">[Sicilia] Agrigento</option>
        <option value="[Sicilia] Caltanissetta">[Sicilia] Caltanissetta</option>
        <option value="[Sicilia] Catania">[Sicilia] Catania</option>
        <option value="[Sicilia] Enna">[Sicilia] Enna</option>
        <option value="[Sicilia] Messina">[Sicilia] Messina</option>
        <option value="[Sicilia] Palermo">[Sicilia] Palermo</option>
        <option value="[Sicilia] Ragusa">[Sicilia] Ragusa</option>
        <option value="[Sicilia] Siracusa">[Sicilia] Siracusa</option>
        <option value="[Sicilia] Trapani">[Sicilia] Trapani</option>
        <option value="[Toscana] Arezzo">[Toscana] Arezzo</option>
        <option value="[Toscana] Firenze">[Toscana] Firenze</option>
        <option value="[Toscana] Grosseto">[Toscana] Grosseto</option>
        <option value="[Toscana] Livorno">[Toscana] Livorno</option>
        <option value="[Toscana] Lucca">[Toscana] Lucca</option>
        <option value="[Toscana] Massa">[Toscana] Massa</option>
        <option value="[Toscana] Pisa">[Toscana] Pisa</option>
        <option value="[Toscana] Pistoia">[Toscana] Pistoia</option>
        <option value="[Toscana] Prato">[Toscana] Prato</option>
        <option value="[Toscana] Siena">[Toscana] Siena</option>
        <option value="[Trentino Alto Adige] Bolzano">[Trentino Alto Adige] Bolzano</option>
        <option value="[Trentino Alto Adige] Trento">[Trentino Alto Adige] Trento</option>
        <option value="[Umbria] Perugia">[Umbria] Perugia</option>
        <option value="[Umbria] Terni">[Umbria] Terni</option>
        <option value="[Valle d'aosta] Aosta">[Valle d'aosta] Aosta</option>
        <option value="[Veneto] Belluno">[Veneto] Belluno</option>
        <option value="[Veneto] Padova">[Veneto] Padova</option>
        <option value="[Veneto] Rovigo">[Veneto] Rovigo</option>
        <option value="[Veneto] Treviso">[Veneto] Treviso</option>
        <option value="[Veneto] Venezia">[Veneto] Venezia</option>
        <option value="[Veneto] Verona">[Veneto] Verona</option>
        <option value="[Veneto] Vicenza">[Veneto] Vicenza</option>
    </select>
</p>