[#include '/_tags_/all.tpl']
[#import '/pages/main.tpl' as page]
[@response.do]
    [@page.do]
        [#include '/blocks/homesx.tpl']
        [#include '/blocks/homedx.tpl']
    [/@page.do]
[/@response.do]